config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  resources :homepages

  resources :short_urls

  delete 'short_urls' => 'short_urls#destroy'

  get "sign_up" => 'users#new', as: "sign_up"
  resources :users

  get "log_in" => 'sessions#new', as: "log_in"
  get "logout" => 'sessions#destroy', as: "logout"
  resources :sessions

  resources :short_visits

  get "/:short_url_id" => "short_visits#short_original_url"

end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
  belongs_to :user
  has_many :short_visits, dependent: :destroy
  validates_presence_of :original_url

  validates_uniqueness_of :original_url
  after_create :generate_short_url
  UNIQUE_SHORT_KEY = 5

  #This method generates a random short url
  def generate_short_url
    charset = ('a'..'z').to_a + (0..9).to_a
    self.shorty = (0...UNIQUE_SHORT_KEY).map{ charset.to_a[rand(charset.size)] }.join
    self.save
  end

  def self.search_shorty(short_url)
    ShortUrl.where(shorty: "#{short_url}")
  end

  def self.update_short_visit_counts(orig_url_record, visit_counts)
    orig_url_record.first.update(visit_counts: visit_counts)
  end
end

app/models/short_visit.rb
class ShortVisit < ActiveRecord::Base
  belongs_to :short_url
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :short_urls, dependent: :destroy

  attr_accessor :password
  before_save :password_encrypt

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email, on: :create
  validates_uniqueness_of :email

  #this method encrypts user password using password digest
  def password_encrypt
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate_user(email,password)
    log_in_user = find_by_email(email)
    if log_in_user && log_in_user.password_hash == BCrypt::Engine.hash_secret(password, log_in_user.password_salt)
      log_in_user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    redirect_to '/log_in' unless current_user
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    session_user = User.authenticate_user(params[:email], params[:password])
    if session_user
      session[:user_id] = session_user.id
      redirect_to short_urls_path, notice: "logged in"
    else
      flash.now.alert = "Invalid User"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil;
    redirect_to root_url, notice: "User succesfully logged out"
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_filter :authenticate_user

  def new
    @short_url = ShortUrl.new
  end

  def create
    @short_url = ShortUrl.new(short_url_params)
    if @short_url.save
      redirect_to short_urls_path
    else
      render 'new'
    end
  end

  def index
    @short_urls = current_user.short_urls
  end

  def destroy
    ShortUrl.find_by_id(params[:id]).destroy
    redirect_to short_urls_path
  end

  private

  def short_url_params
    params.require(:short_url).permit(:original_url,:user_id)
  end
end

app/controllers/short_visits_controller.rb
class ShortVisitsController < ApplicationController
  require 'open-uri'
  before_filter :authenticate_user

  def show
    @short_visit = ShortVisit.where(short_url_id: params[:id])
  end

  #this method fetches short url entered by visitor and stores visitor location in short visits
  def short_original_url
    orig_url = ShortUrl.search_shorty(params[:short_url_id])
    if orig_url.exists?
      visitor_ip = find_remote_ip
      visitor_details = short_visit_location(visitor_ip)
      short_visit = ShortVisit.create(visitor_ip: visitor_details["ip"], visitor_city: visitor_details["city"], visitor_country_iso2: visitor_details["country"]["code"], short_url_id: orig_url.first.id)
      ShortUrl.update_short_visit_counts(orig_url, orig_url.first.visit_counts+=1)
      redirect_to orig_url.first.original_url
    end
  end

  private

  #this method fetches the ip of visitor
  def find_remote_ip
    if request.remote_ip == "::1"
      '216.58.196.100'
    else
      request.remote_ip
    end
  end

  #this method fetches visitor details via a JSON request to below API
  def short_visit_location(visitor_ip)
    response = open("http://geoip.nekudo.com/api/#{visitor_ip}").read
    JSON.parse(response)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to log_in_path
    else
      render 'new'
    end
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit(:uname,:email,:password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/helpers/short_visits_helper.rb
module ShortVisitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/index.html.haml
.container
  .page-header
    .col-lg-8.col-md-7.col-sm-6
      %h1 Url Shortner
      %p.homepage-main-para Make long url's short and easy to access and remember with our Short Url Generator. This application also keeps a track of the user visits to the short url which is generated by you. 

app/views/layouts/_nav_links.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}Url Shortner
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li
            %a
              Hello
              =current_user.uname
          %li
            =link_to "Url Shortner", new_short_url_path
          %li
            =link_to "logout", logout_path
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            =link_to "login", log_in_path
          %li
            =link_to "signup", sign_up_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
          %title Url Shortner
          = stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track"  => true
          = javascript_include_tag "application","data-turbolinks-track"  => true
          = csrf_meta_tags
          -#Bootstrap
          -#%link{:href => "/vendorcss/bootstrap.min.css", :rel => "stylesheet"}
            -#HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
            -#WARNING: Respond.js doesn't work if you view the page via file://
            -#[if lt IE 9]
          %script{src: "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"}
          %script{src: "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"}
          %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
          %script{:src => "http://code.jquery.com/ui/1.11.4/jquery-ui.js"}
          %script{:src => "https://maps.googleapis.com/maps/api/js"}
          %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans+Narrow", :rel => "stylesheet", :type => "text/css"}
  %body
    =render "layouts/nav_links"
    -flash.each do |name,message|
      =content_tag :div, message, id: "flash_#{name}"
    = yield

app/views/short_urls/index.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Url ID
      %th Original URL
      %th Short URL
      %th Visit Counts
      %th Visited Users
      %th Actions
  %tbody
    -@short_urls.each do |url|
      %tr
        %td= url.id
        %td= url.original_url
        %td
          = url.shorty
          %p
          = link_to "View Short Url", "http://localhost:3000/"+url.shorty, target: 'blank', class: "btn btn-primary"
        %td= url.visit_counts
        %td= link_to "Show Visitors", short_visit_path(id: url.id), class: "btn btn-primary"
        %td= link_to "Delete", short_urls_path(id: url.id),data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger"

app/views/short_urls/new.html.haml
.form-wrapper.col-md-10
  =form_for @short_url, url: {action: :create}, html: {class: "form-horizontal"} do |f|
    - if @short_url.errors.any?
      .error_messages
        - @short_url.errors.full_messages.each do |message|
          %div= message
    %fieldset
      %legend Url Shortner
      = f.hidden_field :user_id, value: current_user.id
      .form-group
        .col-md-2
          = f.label :original_url, "Original Url"
        .col-md-8
          = f.text_field :original_url, placeholder: "Enter the Original Url", class: "form-control"
      .form-group
        .col-lg-10.col-lg-offset-2
          %button.btn.btn-primary{:type => "submit"} Generate Short Url

app/views/short_visits/show.html.haml
%table.table.table-striped.table-hover
  %thead
    %tr
      %th Visitor ID
      %th Visitor IP
      %th Visitor City
      %th Visit Country Code
  %tbody
    -@short_visit.each do |visitor|
      %tr
        %td= visitor.id
        %td= visitor.visitor_ip
        %td= visitor.visitor_city
        %td= visitor.visitor_country_iso2

app/views/users/index.html.haml
%h1 Users

app/views/users/new.html.haml
.container
  .user_login_registration_container
    .login-form-wrapper.col-md-4
      .signup_login_form_wrapper
        %h1 Sign Up
        = form_for @user, html: {class: "form-horizontal custom-form"} do |f|
          - if @user.errors.any?
            .error_messages
              %h2 Form is invalid
              %ul
                - for message in @user.errors.full_messages
                  %li= message
          .form-group
            = f.label :uname, class: "control-label"
            %br/
            = f.text_field :uname, autofocus: true, class: "form-control"
          .form-group
            = f.label :email, class: "control-label"
            %br/
            = f.email_field :email, autofocus: true, class: "form-control"
          .form-group
            = f.label :password, class: "control-label"
            %br/
            = f.password_field :password, class: "form-control"
          .form-group
            = f.label :password_confirmation, class: "control-label"
            %br/
            = f.password_field :password_confirmation, class: "form-control"
          .form-group
            = f.submit class: "btn btn-primary custom-form-button"